version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: samuelamt/equipamentos-frontend:latest
    container_name: equipamentos-frontend-container
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
