version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    image: samuelamt/crud-equipamentos:latest
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      dockerfile: Dockerfile
    image: samuelamt/equipamentos-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge